### PR TITLE
Added .travis.yml CI configuration

### PR DESCRIPTION
**Pull request by axiopisty**
For instructions how to enable Travis CI for your github project see:

https://docs.travis-ci.com/user/getting-started/

### CODE REVIEW

**Comment by axiopisty** [comment]
If you decide to merge this you'll have to configure the project settings in github to allow travis ci to integrate with the project. You should set that up first, and then I can update the README.me to point to your repository on the master branch prior to merging.

For an example to see what this will do, you can review the branch in my repository. Everything is configured and working properly.

**Comment by groakley** [comment]
Here's the link https://travis-ci.org/groakley/phase-vocoder-java. Let me know if I need to change any of the settings.

**Comment by daycountysouthdakotagenweb** [comment]
I think everything is setup properly now such that if you merge the pull request your project's README.md file will show the CI build status. That's with the assumptions that you've configured the project to use travis ci.

**Comment by axiopisty** [comment]
I think everything is setup properly now such that if you merge the pull request your project's README.md file will show the CI build status. That's with the assumptions that you've configured the project to use travis ci.

**Pull request merged**
